const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, HeadingLevel, AlignmentType, BorderStyle, WidthType,
  ShadingType, PageNumber, PageBreak, LevelFormat
} = require('/sessions/upbeat-cool-albattani/mnt/outputs/docx_env/lib/node_modules/docx');
const fs = require('fs');

// ── primitives ────────────────────────────────────────────────────────────
const BD = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const BORDERS = { top: BD, bottom: BD, left: BD, right: BD };
const NB = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };
const NO_BORDERS = { top: NB, bottom: NB, left: NB, right: NB };

const h1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: t, font: "Arial" })] });
const h2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: t, font: "Arial" })] });
const h3 = t => new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: t, font: "Arial" })] });
const p = (t, o = {}) => new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text: t || '', font: "Arial", size: 22, ...o })] });
const blank = () => new Paragraph({ children: [new TextRun("")] });
const pb = () => new Paragraph({ children: [new PageBreak()] });
const hr = () => new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "2E75B6", space: 1 } }, children: [new TextRun("")] });

const bullet = (t, lv = 0) => new Paragraph({
  numbering: { reference: "bullets", level: lv },
  spacing: { after: 80 },
  children: [new TextRun({ text: t, font: "Arial", size: 22 })]
});
const num = t => new Paragraph({
  numbering: { reference: "numbers", level: 0 },
  spacing: { after: 80 },
  children: [new TextRun({ text: t, font: "Arial", size: 22 })]
});

// monospace block for code
const code = (lines) => {
  return lines.map(line => new Paragraph({
    spacing: { after: 0 },
    shading: { fill: "F0F0F0", type: ShadingType.CLEAR },
    border: { left: { style: BorderStyle.SINGLE, size: 12, color: "2F5496", space: 4 } },
    indent: { left: 360 },
    children: [new TextRun({ text: line, font: "Courier New", size: 18 })]
  }));
};

// table helpers
const cell = (text, opts = {}) => {
  const { fill = "FFFFFF", bold = false, color = "333333", header = false, width, colSpan } = opts;
  return new TableCell({
    borders: BORDERS,
    ...(colSpan ? { columnSpan: colSpan } : {}),
    ...(width ? { width: { size: width, type: WidthType.DXA } } : {}),
    shading: { fill, type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text: text || '', font: "Arial", size: header ? 20 : 20, bold: bold || header, color: header ? "FFFFFF" : color })] })]
  });
};
const hdrCell = (text, width) => cell(text, { fill: "1F3864", header: true, bold: true, width });
const statusCell = (text, status) => {
  const fills = { good: "C6EFCE", warn: "FFEB9C", bad: "FFC7CE", info: "DDEBF7", neutral: "F2F2F2" };
  const colors = { good: "375623", warn: "9C5700", bad: "9C0006", info: "1F3864", neutral: "333333" };
  return cell(text, { fill: fills[status] || "F2F2F2", color: colors[status] || "333333", bold: true });
};

function tbl(colWidths, rows) {
  return new Table({
    width: { size: colWidths.reduce((a, b) => a + b, 0), type: WidthType.DXA },
    columnWidths: colWidths,
    rows: rows.map(r => new TableRow({ children: r }))
  });
}

// ── document ─────────────────────────────────────────────────────────────
const doc = new Document({
  numbering: {
    config: [
      { reference: "bullets", levels: [
        { level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
        { level: 1, format: LevelFormat.BULLET, text: "◦", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1080, hanging: 360 } } } },
      ]},
      { reference: "numbers", levels: [
        { level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
      ]},
    ]
  },
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 36, bold: true, font: "Arial", color: "1F3864" },
        paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 28, bold: true, font: "Arial", color: "2F5496" },
        paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 24, bold: true, font: "Arial", color: "2F5496" },
        paragraph: { spacing: { before: 200, after: 120 }, outlineLevel: 2 } },
    ]
  },
  sections: [
    // ── COVER ───────────────────────────────────────────────────────────
    {
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      children: [
        blank(), blank(), blank(), blank(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
          children: [new TextRun({ text: "ORDER ASSURANCE", font: "Arial", size: 52, bold: true, color: "1F3864" })] }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 },
          children: [new TextRun({ text: "Architecture Redesign Specification", font: "Arial", size: 36, color: "2F5496" })] }),
        hr(),
        blank(),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 },
          children: [new TextRun({ text: "ADR-001: PostgreSQL + Alembic  ·  ADR-002: Async OCR Queue  ·  ADR-003: Verification Engine", font: "Arial", size: 22, italics: true, color: "595959" })] }),
        blank(), blank(), blank(), blank(),
        new Paragraph({ alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "Date: June 19, 2026    |    Status: PROPOSED    |    Classification: Internal", font: "Arial", size: 22, color: "595959" })] }),
        pb()
      ]
    },
    // ── MAIN ────────────────────────────────────────────────────────────
    {
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      headers: { default: new Header({ children: [new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "2F5496", space: 1 } },
        children: [new TextRun({ text: "Order Assurance — Architecture Redesign  |  June 2026", font: "Arial", size: 18, color: "2F5496" })]
      })] }) },
      footers: { default: new Footer({ children: [new Paragraph({
        border: { top: { style: BorderStyle.SINGLE, size: 4, color: "2F5496", space: 1 } },
        children: [
          new TextRun({ text: "Confidential  |  amasQIS.ai     Page ", font: "Arial", size: 18, color: "595959" }),
          new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 18, color: "595959" }),
        ]
      })] }) },
      children: [

        // ══ 1. Overview ════════════════════════════════════════════════
        h1("1. Overview"),
        p("This document is the architecture redesign specification for the Order Assurance platform. It covers three self-contained architectural changes that collectively transition the platform from a single-user local prototype to a production-ready, team-facing application:"),
        blank(),
        tbl([500, 2400, 6460], [
          [hdrCell("#", 500), hdrCell("ADR", 2400), hdrCell("What Changes", 6460)],
          [cell("001"), cell("PostgreSQL + Alembic"), cell("Replace SQLite with PostgreSQL 16. Replace custom migration runner with Alembic. Add Docker Compose service.")],
          [cell("002"), cell("Async OCR Queue"), cell("Replace in-process threading queue with Celery 5 workers backed by Redis 7 broker. API becomes fully non-blocking.")],
          [cell("003"), cell("Verification Engine"), cell("Add configurable tolerance thresholds, line-item matching, and a vendor master registry with GST validation.")],
        ]),
        blank(),
        p("These three ADRs are independent and can be implemented in sequence. Each includes: context, decision, consequences, schema/API contracts, and an implementation checklist."),
        blank(),

        // ══ 2. Current State Baseline ══════════════════════════════════
        h1("2. Current State Baseline"),
        p("This section documents precisely what exists today so that ADR authors and implementers have a shared starting point."),
        blank(),

        h2("2.1 Database Layer (database.py)"),
        p("The current engine is created synchronously at module import time:"),
        blank(),
        ...code([
          "# backend/app/database.py (current)",
          "_SQLITE_CONNECT_ARGS = {\"check_same_thread\": False, \"timeout\": 60}",
          "",
          "_engine = create_engine(",
          "    settings.database_url,",
          "    connect_args=_SQLITE_CONNECT_ARGS if settings.database_url.startswith(\"sqlite\") else {},",
          ")",
          "SessionLocal = sessionmaker(bind=_engine, autoflush=False, autocommit=False)",
        ]),
        blank(),
        p("The DATABASE_URL in production .env is: sqlite:///./order_assurance.db"),
        p("Migrations are applied by a custom incremental runner that processes SQL files from the migrations/ directory. There is no Alembic, no downgrade support, and no auto-generation of schema diffs."),
        blank(),

        h2("2.2 ORM Models (app/models/)"),
        blank(),
        tbl([2400, 3000, 4060], [
          [hdrCell("Model", 2400), hdrCell("Table", 3000), hdrCell("Key Columns", 4060)],
          [cell("OrderBundleRecord"), cell("order_bundles"), cell("id (UUID str), bundle_number, customer_name, so_no, status, customer_delivery_status, vendor_procurement_status, created_at, updated_at")],
          [cell("DocumentRecord"), cell("bundle_documents"), cell("id, order_bundle_id (FK), document_type, filename, content_type, storage_path, status, last_error, created_at, updated_at")],
          [cell("DocumentMetadataRecord"), cell("document_metadata"), cell("id, document_id (FK 1:1), field data as JSON/Text, extraction method, confidence scores")],
          [cell("AuditEventRecord"), cell("audit_events"), cell("id, bundle_id, document_id, event_type, payload JSON, created_at")],
          [cell("ReferenceIndexRecord"), cell("reference_index"), cell("id, bundle_id, field_name, field_value, document_type, document_id")],
          [cell("DocumentPageRecord"), cell("document_pages"), cell("id, document_id (FK), page_number, image_path, width, height")],
          [cell("TextSourceRecord"), cell("text_sources"), cell("id, document_id (FK), source_type, raw_text, page_number")],
          [cell("FieldCandidateRecord"), cell("field_candidates"), cell("id, document_id (FK), field_name, value, confidence, source, bbox JSON")],
        ]),
        blank(),

        h2("2.3 Extraction Queue (extraction_queue.py)"),
        p("The current queue is an in-process Python object using threading.Condition + collections.deque. It is initialised once at app startup and held in memory:"),
        blank(),
        ...code([
          "# Current: in-process, non-persistent",
          "class OcrExtractionQueue:",
          "    def __init__(self):",
          "        self._condition = threading.Condition()",
          "        self._queued: deque[_QueueJob] = deque()",
          "        self._active: dict[str, _QueueJob] = {}",
          "",
          "    @contextmanager",
          "    def acquire(self, *, document_id, filename, provider,",
          "                enabled, max_concurrent, max_size, timeout_seconds):",
          "        # blocks the calling async task until a slot is free",
          "        ...",
        ]),
        blank(),
        p("Key limitations of the current approach:"),
        bullet("Queue is lost on process restart — in-flight extractions become EXTRACTION_FAILED with no retry"),
        bullet("max_concurrent=1 is enforced globally — one slow GPU job blocks all other documents"),
        bullet("The asyncio event loop is blocked while the OCR worker thread runs"),
        bullet("No visibility into queue state without custom /api/extractions endpoint"),
        blank(),

        h2("2.4 Verifier Hard-Coded Tolerance"),
        p("The _add_amount_check function in order_bundle_verifier.py uses a hard-coded ±2 currency unit tolerance:"),
        blank(),
        ...code([
          "def _add_amount_check(checks, left, right, left_key, right_key, check_id, fallback_right=None):",
          "    ...",
          "    elif abs(left_value - right_value) <= 2:   # <-- hard-coded, no config",
          "        result = \"PASS\"",
          "        message = \"Amounts match within rounding tolerance.\"",
          "    else:",
          "        result = \"REVIEW_REQUIRED\"",
          "        ...",
        ]),
        blank(),
        p("There is no line-item extraction, no line-item schema, and no vendor master table. The verifier only reads fields from NormalizedDocument.fields (a flat string dict)."),
        blank(),

        pb(),

        // ══ ADR-001 ════════════════════════════════════════════════════
        h1("ADR-001: PostgreSQL 16 + Alembic"),
        blank(),
        tbl([2400, 7060], [
          [hdrCell("Attribute", 2400), hdrCell("Value", 7060)],
          [cell("Status"), statusCell("PROPOSED", "warn")],
          [cell("Date"), cell("June 19, 2026")],
          [cell("Author"), cell("amasQIS.ai Architecture Review")],
          [cell("Priority"), statusCell("CRITICAL — implement first", "bad")],
          [cell("Effort"), statusCell("Medium (3–5 days)", "warn")],
          [cell("Affects"), cell("backend/app/database.py, backend/app/models/, docker-compose.yml, .env, all tests")],
        ]),
        blank(),

        h2("Context"),
        p("SQLite is not safe for production use with concurrent writes. The current setup uses check_same_thread=False with a 60-second timeout — this prevents Python threading errors but does not prevent SQLite file-level write locking. With two simultaneous document uploads or extraction jobs, one will silently time out or corrupt a write operation."),
        p("Additionally, the custom migration runner cannot generate schema diffs, has no downgrade support, and has no conflict resolution for branched development. As the schema grows (vendor master, line items, user auth), this becomes a maintenance liability."),
        blank(),

        h2("Decision"),
        p("Replace SQLite with PostgreSQL 16. Add a docker-compose.yml that provides a postgres service for both development and production. Replace the custom migration runner with Alembic, importing existing hand-written migrations as a single baseline revision."),
        blank(),

        h2("Architecture: Target State"),
        blank(),
        ...code([
          "┌──────────────────────────────────────────────────────────┐",
          "│                   docker-compose.yml                    │",
          "│                                                          │",
          "│   ┌─────────────┐         ┌──────────────────────────┐ │",
          "│   │   backend   │──────── │    postgres:16           │ │",
          "│   │  (FastAPI)  │  5432   │    order_assurance db    │ │",
          "│   └─────────────┘         └──────────────────────────┘ │",
          "│         │                                               │",
          "│   ┌─────────────┐                                       │",
          "│   │  frontend   │                                       │",
          "│   │  (Vite dev) │                                       │",
          "│   └─────────────┘                                       │",
          "└──────────────────────────────────────────────────────────┘",
        ]),
        blank(),

        h2("Changes Required"),

        h3("1. docker-compose.yml (new file)"),
        blank(),
        ...code([
          "version: \"3.9\"",
          "services:",
          "  db:",
          "    image: postgres:16-alpine",
          "    restart: unless-stopped",
          "    environment:",
          "      POSTGRES_DB: order_assurance",
          "      POSTGRES_USER: oa_user",
          "      POSTGRES_PASSWORD: ${DB_PASSWORD}",
          "    volumes:",
          "      - pgdata:/var/lib/postgresql/data",
          "    ports:",
          "      - \"5432:5432\"",
          "    healthcheck:",
          "      test: [\"CMD-SHELL\", \"pg_isready -U oa_user -d order_assurance\"]",
          "      interval: 5s",
          "      retries: 10",
          "",
          "  backend:",
          "    build: ./backend",
          "    depends_on:",
          "      db:",
          "        condition: service_healthy",
          "    environment:",
          "      DATABASE_URL: postgresql://oa_user:${DB_PASSWORD}@db:5432/order_assurance",
          "    env_file: .env",
          "    ports:",
          "      - \"8000:8000\"",
          "    volumes:",
          "      - ./document_store:/app/document_store",
          "",
          "  frontend:",
          "    build: ./frontend",
          "    ports:",
          "      - \"5180:5180\"",
          "",
          "volumes:",
          "  pgdata:",
        ]),
        blank(),

        h3("2. backend/app/database.py (replace SQLite-specific code)"),
        blank(),
        ...code([
          "# backend/app/database.py (target)",
          "from sqlalchemy import create_engine, text, pool",
          "from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker",
          "",
          "class Base(DeclarativeBase):",
          "    pass",
          "",
          "def _make_engine(url: str):",
          "    return create_engine(",
          "        url,",
          "        pool_size=10,",
          "        max_overflow=20,",
          "        pool_pre_ping=True,        # auto-reconnect on stale connections",
          "        pool_recycle=3600,         # recycle connections every 1h",
          "    )",
          "",
          "_engine = _make_engine(settings.database_url)",
          "SessionLocal = sessionmaker(bind=_engine, autoflush=False, autocommit=False)",
          "",
          "def get_db() -> Generator[Session, None, None]:",
          "    db = SessionLocal()",
          "    try:",
          "        yield db",
          "    finally:",
          "        db.close()",
        ]),
        blank(),

        h3("3. Alembic Setup"),
        blank(),
        ...code([
          "# Install",
          "pip install alembic psycopg2-binary",
          "",
          "# Initialise in backend/",
          "cd backend",
          "alembic init alembic",
          "",
          "# alembic/env.py — point at our Base",
          "from app.database import Base",
          "from app import models  # noqa — registers all models",
          "target_metadata = Base.metadata",
          "",
          "# alembic.ini — use env var for URL",
          "sqlalchemy.url = %(DATABASE_URL)s",
          "",
          "# Create baseline revision from current schema",
          "alembic revision --autogenerate -m \"baseline_from_v1_migrations\"",
          "# Review generated file, then:",
          "alembic upgrade head",
        ]),
        blank(),
        p("The baseline revision will capture the full schema from the 8 existing ORM models. Subsequent ADR-003 changes (vendor master, line items) will each add a new Alembic revision."),
        blank(),

        h3("4. .env Changes"),
        blank(),
        ...code([
          "# .env (production)",
          "DATABASE_URL=postgresql://oa_user:${DB_PASSWORD}@localhost:5432/order_assurance",
          "DB_PASSWORD=<strong-random-password>",
          "",
          "# Remove:",
          "# DATABASE_URL=sqlite:///./order_assurance.db",
        ]),
        blank(),

        h3("5. ORM Model Adjustments"),
        p("The existing models use String(36) UUIDs as primary keys. In PostgreSQL, switch to native UUID type for performance:"),
        blank(),
        ...code([
          "# Before (SQLite-compatible)",
          "from sqlalchemy import String",
          "id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))",
          "",
          "# After (PostgreSQL native UUID)",
          "from sqlalchemy.dialects.postgresql import UUID as PG_UUID",
          "import uuid",
          "id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)",
        ]),
        blank(),
        p("Apply this to all 8 model files in a single Alembic revision. API layer already serialises IDs to strings — no API contract change required."),
        blank(),

        h3("6. Test Configuration"),
        blank(),
        ...code([
          "# backend/tests/conftest.py",
          "# Use a separate test database, not the production one",
          "TEST_DB_URL = \"postgresql://oa_user:test_pw@localhost:5432/order_assurance_test\"",
          "",
          "# Or keep SQLite for tests (faster, CI-friendly):",
          "# Only backend/tests may use SQLite — never production code",
          "TEST_DB_URL = \"sqlite:///./test_order_assurance.db\"",
          "",
          "@pytest.fixture(scope=\"session\")",
          "def engine():",
          "    engine = create_engine(TEST_DB_URL, connect_args={\"check_same_thread\": False})",
          "    Base.metadata.create_all(engine)",
          "    yield engine",
          "    Base.metadata.drop_all(engine)",
        ]),
        blank(),

        h2("Consequences"),
        bullet("Concurrent writes are now safe. PostgreSQL uses row-level locking instead of file-level locking."),
        bullet("Connection pooling (pool_size=10) supports multiple simultaneous API requests."),
        bullet("Alembic auto-generates migration files from model changes. No hand-writing SQL."),
        bullet("docker-compose up spins up a complete dev environment in one command."),
        bullet("Existing SQLite data cannot be automatically migrated. A one-time pgloader script is needed for existing bundles."),
        bullet("CI/CD must provision a PostgreSQL instance (Docker service in GitHub Actions is one-line config)."),
        blank(),

        h2("Implementation Checklist"),
        num("Add psycopg2-binary to backend/requirements.txt"),
        num("Create docker-compose.yml with postgres:16 and backend services"),
        num("Update backend/app/database.py — remove SQLite-specific connect args, add pool config"),
        num("Run: cd backend && alembic init alembic"),
        num("Configure alembic/env.py to use Base.metadata and DATABASE_URL env var"),
        num("Run: alembic revision --autogenerate -m baseline_from_v1_migrations"),
        num("Review baseline migration file — verify all 8 tables are captured"),
        num("Update all ORM model primary key columns to PostgreSQL UUID type"),
        num("Add UUID migration as second revision: alembic revision --autogenerate -m uuid_pk_to_native"),
        num("Update .env — set DATABASE_URL to postgresql://... and add DB_PASSWORD"),
        num("Run: docker-compose up -d db && alembic upgrade head"),
        num("Run full backend test suite: python -m pytest tests -q — record pass/skip/fail count"),
        num("Run migration tests: python -m pytest tests/integration/test_migrations.py -q"),
        num("Confirm no extraction/parser/OCR/verification/export behavior changed"),
        blank(),

        pb(),

        // ══ ADR-002 ════════════════════════════════════════════════════
        h1("ADR-002: Async OCR Queue — Celery 5 + Redis 7"),
        blank(),
        tbl([2400, 7060], [
          [hdrCell("Attribute", 2400), hdrCell("Value", 7060)],
          [cell("Status"), statusCell("PROPOSED", "warn")],
          [cell("Date"), cell("June 19, 2026")],
          [cell("Priority"), statusCell("HIGH — implement after ADR-001", "warn")],
          [cell("Effort"), statusCell("High (5–8 days)", "bad")],
          [cell("Affects"), cell("backend/app/services/extraction_queue.py, extraction_service.py, api/routes/documents.py, api/routes/extractions.py (new), docker-compose.yml, frontend polling")],
        ]),
        blank(),

        h2("Context"),
        p("The current extraction queue (OcrExtractionQueue) is a threading.Condition + deque held in process memory. This has three critical problems:"),
        bullet("Non-persistent: restarting the API server discards all queued and active jobs, leaving documents stuck in EXTRACTING status with no recovery path."),
        bullet("Event loop blocking: OCR work runs on a background thread while FastAPI awaits it. Under load, this blocks the entire event loop, degrading API responsiveness for all other requests."),
        bullet("No retry: if PaddleOCR crashes or the GPU goes OOM, the job is permanently lost."),
        blank(),
        p("PaddleOCR GPU (PP-OCRv4) is a CPU/GPU-intensive process that takes 3–30 seconds per page depending on image quality. This work must happen outside the API process."),
        blank(),

        h2("Decision"),
        p("Replace the in-process queue with Celery 5 workers using Redis 7 as both the message broker and result backend. The API becomes a task producer only — it submits a job and returns immediately with a task_id. Clients poll a new status endpoint."),
        blank(),

        h2("Architecture: Target State"),
        blank(),
        ...code([
          "┌─────────────────────────────────────────────────────────────────────┐",
          "│                         docker-compose.yml                          │",
          "│                                                                     │",
          "│  ┌──────────────┐   enqueue    ┌─────────────────────────────────┐ │",
          "│  │   FastAPI    │─────────────►│         Redis 7 (broker)        │ │",
          "│  │   backend    │              │   task queue: oa.extraction     │ │",
          "│  │              │◄─────────────│   result backend: oa.results    │ │",
          "│  │  POST /docs  │  task_id     └───────────────┬─────────────────┘ │",
          "│  │  GET /status │                              │ consume           │",
          "│  └──────────────┘              ┌───────────────▼─────────────────┐ │",
          "│                                │     Celery Worker Process       │ │",
          "│                                │     concurrency=1               │ │",
          "│                                │     (GPU-bound, one at a time)  │ │",
          "│                                │                                 │ │",
          "│                                │  extract_document_task()        │ │",
          "│                                │    → PaddleOCR GPU / GLM        │ │",
          "│                                │    → structured_text_parser     │ │",
          "│                                │    → DB write                   │ │",
          "│                                └─────────────────────────────────┘ │",
          "└─────────────────────────────────────────────────────────────────────┘",
        ]),
        blank(),

        h2("Changes Required"),

        h3("1. Add Redis to docker-compose.yml"),
        blank(),
        ...code([
          "  redis:",
          "    image: redis:7-alpine",
          "    restart: unless-stopped",
          "    ports:",
          "      - \"6379:6379\"",
          "    volumes:",
          "      - redis_data:/data",
          "    command: redis-server --save 60 1 --loglevel warning",
          "",
          "  celery_worker:",
          "    build: ./backend",
          "    command: celery -A app.celery_app worker --concurrency=1 --loglevel=info",
          "    depends_on:",
          "      - redis",
          "      - db",
          "    environment:",
          "      CELERY_BROKER_URL: redis://redis:6379/0",
          "      CELERY_RESULT_BACKEND: redis://redis:6379/1",
          "      DATABASE_URL: postgresql://oa_user:${DB_PASSWORD}@db:5432/order_assurance",
          "    env_file: .env",
          "    volumes:",
          "      - ./document_store:/app/document_store",
          "",
          "volumes:",
          "  redis_data:",
        ]),
        blank(),

        h3("2. backend/app/celery_app.py (new file)"),
        blank(),
        ...code([
          "from celery import Celery",
          "from app.config import settings",
          "",
          "celery_app = Celery(",
          "    \"order_assurance\",",
          "    broker=settings.celery_broker_url,",
          "    backend=settings.celery_result_backend,",
          "    include=[\"app.tasks.extraction_tasks\"],",
          ")",
          "",
          "celery_app.conf.update(",
          "    task_serializer=\"json\",",
          "    result_serializer=\"json\",",
          "    accept_content=[\"json\"],",
          "    task_track_started=True,",
          "    task_acks_late=True,           # ack only after completion (safe retry)",
          "    worker_prefetch_multiplier=1,  # one task at a time per worker",
          "    task_routes={",
          "        \"app.tasks.extraction_tasks.*\": {\"queue\": \"oa.extraction\"},",
          "    },",
          ")",
        ]),
        blank(),

        h3("3. backend/app/tasks/extraction_tasks.py (new file)"),
        blank(),
        ...code([
          "from celery import shared_task",
          "from celery.utils.log import get_task_logger",
          "from app.database import SessionLocal",
          "from app.services.extraction_service import run_extraction_for_document",
          "",
          "logger = get_task_logger(__name__)",
          "",
          "@shared_task(",
          "    bind=True,",
          "    name=\"app.tasks.extraction_tasks.extract_document\",",
          "    max_retries=3,",
          "    default_retry_delay=30,        # 30s between retries",
          "    autoretry_for=(Exception,),",
          "    retry_backoff=True,            # exponential: 30s, 60s, 120s",
          "    retry_jitter=True,",
          ")",
          "def extract_document(self, document_id: str, bundle_id: str) -> dict:",
          "    logger.info(f\"Starting extraction: document={document_id}\")",
          "    db = SessionLocal()",
          "    try:",
          "        result = run_extraction_for_document(",
          "            db=db,",
          "            document_id=document_id,",
          "            bundle_id=bundle_id,",
          "        )",
          "        return {\"status\": \"completed\", \"document_id\": document_id, **result}",
          "    except Exception as exc:",
          "        logger.error(f\"Extraction failed: {exc}\")",
          "        raise self.retry(exc=exc)",
          "    finally:",
          "        db.close()",
        ]),
        blank(),

        h3("4. API Contract Changes"),
        p("Current: POST /api/documents/{id}/extract runs OCR synchronously and returns extracted fields."),
        p("Target: POST /api/documents/{id}/extract enqueues the job and returns immediately:"),
        blank(),
        ...code([
          "# Response from POST /api/documents/{id}/extract (new)",
          "{",
          "  \"task_id\": \"3e2f1a...\",",
          "  \"document_id\": \"uuid-...\",",
          "  \"status\": \"queued\",",
          "  \"queue_position\": 2,",
          "  \"estimated_start_seconds\": 45",
          "}",
          "",
          "# New endpoint: GET /api/documents/{id}/extraction-status",
          "{",
          "  \"task_id\": \"3e2f1a...\",",
          "  \"document_id\": \"uuid-...\",",
          "  \"status\": \"started\" | \"queued\" | \"completed\" | \"failed\",",
          "  \"started_at\": \"2026-06-19T10:00:00Z\",",
          "  \"completed_at\": \"2026-06-19T10:00:45Z\",",
          "  \"error\": null",
          "}",
        ]),
        blank(),

        h3("5. backend/app/api/routes/documents.py (changes)"),
        blank(),
        ...code([
          "from app.tasks.extraction_tasks import extract_document as extract_task",
          "",
          "@router.post(\"/{document_id}/extract\")",
          "def trigger_extraction(document_id: str, db: Session = Depends(get_db)):",
          "    doc = _get_document_or_404(document_id, db)",
          "    # Update status immediately",
          "    doc.status = \"EXTRACTING\"",
          "    db.commit()",
          "    # Enqueue — returns AsyncResult immediately, does NOT block",
          "    task = extract_task.delay(document_id=str(doc.id), bundle_id=str(doc.order_bundle_id))",
          "    return {",
          "        \"task_id\": task.id,",
          "        \"document_id\": document_id,",
          "        \"status\": \"queued\",",
          "    }",
          "",
          "@router.get(\"/{document_id}/extraction-status\")",
          "def get_extraction_status(document_id: str):",
          "    from app.celery_app import celery_app",
          "    # Find the latest task for this document",
          "    result = celery_app.AsyncResult(task_id)",
          "    return {\"status\": result.state.lower(), ...}",
        ]),
        blank(),

        h3("6. Frontend Changes (minimal)"),
        p("The frontend already polls extraction status via ExtractionActivityJob. The polling logic in ExtractionReviewPage.tsx needs to be updated to:"),
        bullet("POST /extract → capture task_id from response"),
        bullet("Poll GET /documents/{id}/extraction-status using task_id"),
        bullet("Show 'queued (position N)' state while waiting"),
        bullet("On 'completed', reload extracted fields panel"),
        blank(),
        p("The existing ExtractionActivityJob TypeScript type should be extended:"),
        blank(),
        ...code([
          "// frontend/src/types/api.ts (extend)",
          "export interface ExtractionJobStatus {",
          "  task_id: string;",
          "  document_id: string;",
          "  status: 'queued' | 'started' | 'completed' | 'failed';",
          "  queue_position?: number;",
          "  started_at?: string;",
          "  completed_at?: string;",
          "  error?: string;",
          "}",
        ]),
        blank(),

        h3("7. Config Additions (app/config.py)"),
        blank(),
        ...code([
          "# Add to Settings dataclass",
          "celery_broker_url: str = field(default_factory=lambda: os.getenv(",
          "    \"CELERY_BROKER_URL\", \"redis://localhost:6379/0\"",
          "))",
          "celery_result_backend: str = field(default_factory=lambda: os.getenv(",
          "    \"CELERY_RESULT_BACKEND\", \"redis://localhost:6379/1\"",
          "))",
        ]),
        blank(),

        h2("Consequences"),
        bullet("API is fully non-blocking. Extraction jobs no longer compete with API response time."),
        bullet("Queue survives process restart. Redis persists tasks; worker picks them up on restart."),
        bullet("Automatic retry on failure (max 3 attempts, exponential backoff)."),
        bullet("Concurrency is still 1 (GPU-bound). Set to 2 if running dual-GPU or for CPU-OCR use."),
        bullet("Redis adds a new infrastructure dependency. Add to docker-compose — minimal operational overhead."),
        bullet("The existing in-process OcrExtractionQueue class can be deleted or kept as a test double."),
        bullet("Flower dashboard (pip install flower) provides real-time queue monitoring at http://localhost:5555."),
        blank(),

        h2("Implementation Checklist"),
        num("Add celery[redis] to backend/requirements.txt"),
        num("Add Redis service to docker-compose.yml"),
        num("Add Celery worker service to docker-compose.yml (concurrency=1)"),
        num("Create backend/app/celery_app.py with broker/backend configuration"),
        num("Create backend/app/tasks/__init__.py and extraction_tasks.py"),
        num("Add celery_broker_url and celery_result_backend to app/config.py Settings"),
        num("Update POST /documents/{id}/extract to enqueue task and return task_id"),
        num("Add GET /documents/{id}/extraction-status endpoint"),
        num("Remove or archive the synchronous OcrExtractionQueue acquire() call from extraction_service.py"),
        num("Update frontend ExtractionActivityJob type and polling logic"),
        num("Run full backend test suite: python -m pytest tests -q — record pass/skip/fail count"),
        num("Run real-document validation: all three baselines (Panimalar, Trade, AMC) must pass"),
        num("Confirm extraction/parser/OCR/export behavior unchanged"),
        blank(),

        pb(),

        // ══ ADR-003 ════════════════════════════════════════════════════
        h1("ADR-003: Verification Engine — Tolerance, Line-Item Matching & Vendor Master"),
        blank(),
        tbl([2400, 7060], [
          [hdrCell("Attribute", 2400), hdrCell("Value", 7060)],
          [cell("Status"), statusCell("PROPOSED", "warn")],
          [cell("Date"), cell("June 19, 2026")],
          [cell("Priority"), statusCell("HIGH — implement after ADR-001", "warn")],
          [cell("Effort"), statusCell("High (7–10 days)", "bad")],
          [cell("Affects"), cell("order_bundle_verifier.py, document_normalizer.py, models/ (new: vendor, line_item), extraction parser, api/routes/vendors.py (new)")],
        ]),
        blank(),

        h2("Context"),
        p("The current verification engine has three specific limitations:"),
        num("Tolerance is hard-coded to ±2 currency units (abs(left - right) <= 2). This is wrong for large invoices where ±0.5% is acceptable but ±2 absolute is too loose or too tight depending on the invoice amount."),
        num("Line-item matching is explicitly absent. The verifier compares only header-level totals. Industry standard 3-way matching requires line-by-line SKU + quantity + price reconciliation."),
        num("There is no vendor master. The verifier cannot validate that a vendor's GST number, legal name, or bank account matches a trusted registry — creating a payment fraud risk."),
        blank(),

        h2("Decision"),
        p("This ADR makes three changes, each independently deployable but designed as a cohesive upgrade:"),
        num("Replace hard-coded ±2 tolerance with a configurable ToleranceConfig (percentage-based, per check type)."),
        num("Add a LineItem data model and extraction schema, and extend the verifier to perform line-item reconciliation."),
        num("Add a Vendor master ORM model and a VendorValidationService that gates vendor checks against registered data."),
        blank(),

        h2("Change 1: Configurable Tolerance"),

        h3("Current Code (order_bundle_verifier.py, line ~339)"),
        blank(),
        ...code([
          "elif abs(left_value - right_value) <= 2:   # hard-coded ±2 units",
          "    result = \"PASS\"",
        ]),
        blank(),

        h3("Target: ToleranceConfig"),
        blank(),
        ...code([
          "# backend/app/services/tolerance_config.py (new)",
          "from dataclasses import dataclass",
          "",
          "@dataclass(frozen=True)",
          "class ToleranceConfig:",
          "    \"\"\"All amounts compared with percentage tolerance, not fixed units.\"\"\"",
          "    # Configurable per check type",
          "    customer_po_invoice_pct: float = 0.02    # 2% — header totals may have tax",
          "    vendor_po_invoice_pct: float = 0.01      # 1% — tighter for vendor side",
          "    dc_invoice_pct: float = 0.01             # 1% — DC vs invoice amount",
          "    line_item_qty_pct: float = 0.0           # 0% — quantity must be exact",
          "    line_item_price_pct: float = 0.005       # 0.5% — unit price",
          "",
          "    def within(self, check_type: str, left: float, right: float) -> bool:",
          "        pct = getattr(self, f\"{check_type}_pct\", 0.02)",
          "        if left == 0 and right == 0:",
          "            return True",
          "        avg = (abs(left) + abs(right)) / 2",
          "        return abs(left - right) <= (avg * pct) if avg > 0 else left == right",
          "",
          "",
          "# Singleton loaded from config",
          "DEFAULT_TOLERANCE = ToleranceConfig()",
        ]),
        blank(),
        ...code([
          "# order_bundle_verifier.py — _add_amount_check (updated)",
          "def _add_amount_check(checks, left, right, left_key, right_key,",
          "                      check_id, fallback_right=None,",
          "                      tolerance: ToleranceConfig = DEFAULT_TOLERANCE,",
          "                      tolerance_key: str = \"customer_po_invoice\"):",
          "    ...",
          "    elif tolerance.within(tolerance_key, left_value, right_value):",
          "        result = \"PASS\"",
          "        message = f\"Amounts match within {getattr(tolerance, tolerance_key + '_pct')*100:.1f}% tolerance.\"",
        ]),
        blank(),
        p("Tolerance values are environment-configurable via .env (TOLERANCE_CUSTOMER_PO_PCT=0.02 etc.) and exposed in the Settings dataclass."),
        blank(),

        h2("Change 2: Line-Item Matching"),

        h3("2a. LineItem Data Model (new ORM table)"),
        blank(),
        ...code([
          "# backend/app/models/line_item.py (new)",
          "class LineItemRecord(Base):",
          "    __tablename__ = \"line_items\"",
          "",
          "    id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)",
          "    document_id: Mapped[uuid.UUID] = mapped_column(ForeignKey(\"bundle_documents.id\"), index=True)",
          "    line_number: Mapped[int]",
          "    description: Mapped[str | None] = mapped_column(Text, nullable=True)",
          "    hsn_sac: Mapped[str | None] = mapped_column(String(20), nullable=True)  # Indian HSN/SAC code",
          "    quantity: Mapped[float | None] = mapped_column(Float, nullable=True)",
          "    unit: Mapped[str | None] = mapped_column(String(20), nullable=True)",
          "    unit_price: Mapped[float | None] = mapped_column(Float, nullable=True)",
          "    amount: Mapped[float | None] = mapped_column(Float, nullable=True)",
          "    tax_rate: Mapped[float | None] = mapped_column(Float, nullable=True)",
          "    tax_amount: Mapped[float | None] = mapped_column(Float, nullable=True)",
          "    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), ...)",
          "",
          "    document = relationship(\"DocumentRecord\", back_populates=\"line_items\")",
        ]),
        blank(),

        h3("2b. Alembic Revision for line_items table"),
        blank(),
        ...code([
          "alembic revision --autogenerate -m add_line_items_table",
          "alembic upgrade head",
        ]),
        blank(),

        h3("2c. Parser Extension for Line-Item Extraction"),
        p("The structured text parser currently extracts only named fields from document text. It must be extended to detect table structures and extract rows:"),
        blank(),
        ...code([
          "# backend/app/services/extraction/line_item_parser.py (new)",
          "import re",
          "from dataclasses import dataclass",
          "",
          "@dataclass",
          "class ParsedLineItem:",
          "    line_number: int",
          "    description: str | None",
          "    hsn_sac: str | None",
          "    quantity: float | None",
          "    unit: str | None",
          "    unit_price: float | None",
          "    amount: float | None",
          "",
          "def parse_line_items(raw_text: str) -> list[ParsedLineItem]:",
          "    \"\"\"",
          "    Detect tabular section in vendor invoice / PO text.",
          "    Strategy: find header row (Sl No | Description | HSN | Qty | Rate | Amount)",
          "    then extract each data row below it until a subtotal sentinel is detected.",
          "    \"\"\"",
          "    ...",
        ]),
        blank(),

        h3("2d. Verifier Extension — Line-Item Reconciliation"),
        blank(),
        ...code([
          "# order_bundle_verifier.py — new check",
          "def _line_item_match(vendor_po_items, vendor_invoice_items, checks, issues, tolerance):",
          "    \"\"\"",
          "    Match line items from Vendor PO against Vendor Invoice.",
          "    Uses description similarity (SequenceMatcher) + HSN/SAC code as primary key.",
          "    Flags: QUANTITY_MISMATCH, PRICE_MISMATCH, ITEM_NOT_FOUND, EXTRA_ITEM",
          "    \"\"\"",
          "    unmatched_po = list(vendor_po_items)",
          "    for inv_item in vendor_invoice_items:",
          "        match = _find_best_match(inv_item, unmatched_po)",
          "        if not match:",
          "            issues.append({\"code\": \"LINE_ITEM_NOT_IN_PO\", ..., \"severity\": \"BLOCKER\"})",
          "            continue",
          "        if not tolerance.within(\"line_item_qty\", match.quantity, inv_item.quantity):",
          "            issues.append({\"code\": \"LINE_ITEM_QTY_MISMATCH\", ..., \"severity\": \"BLOCKER\"})",
          "        if not tolerance.within(\"line_item_price\", match.unit_price, inv_item.unit_price):",
          "            issues.append({\"code\": \"LINE_ITEM_PRICE_MISMATCH\", ..., \"severity\": \"WARNING\"})",
          "        unmatched_po.remove(match)",
          "    for remaining in unmatched_po:",
          "        issues.append({\"code\": \"PO_ITEM_NOT_IN_INVOICE\", ..., \"severity\": \"WARNING\"})",
        ]),
        blank(),

        h2("Change 3: Vendor Master"),

        h3("3a. Vendor ORM Model (new)"),
        blank(),
        ...code([
          "# backend/app/models/vendor.py (new)",
          "class VendorRecord(Base):",
          "    __tablename__ = \"vendors\"",
          "",
          "    id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)",
          "    gstin: Mapped[str] = mapped_column(String(15), unique=True, index=True)  # Indian GST Number",
          "    legal_name: Mapped[str] = mapped_column(String(255))  # As per GST registration",
          "    trade_name: Mapped[str | None] = mapped_column(String(255), nullable=True)",
          "    pan: Mapped[str | None] = mapped_column(String(10), nullable=True)",
          "    bank_account_no: Mapped[str | None] = mapped_column(String(30), nullable=True)",
          "    bank_ifsc: Mapped[str | None] = mapped_column(String(11), nullable=True)",
          "    is_active: Mapped[bool] = mapped_column(default=True)",
          "    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), ...)",
          "    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), ...)",
        ]),
        blank(),

        h3("3b. API: Vendor Master CRUD (new route file)"),
        blank(),
        ...code([
          "# backend/app/api/routes/vendors.py (new)",
          "router = APIRouter(prefix=\"/api/vendors\", tags=[\"vendors\"])",
          "",
          "@router.post(\"/\")          # Create vendor",
          "@router.get(\"/\")           # List vendors (search by gstin, name)",
          "@router.get(\"/{id}\")        # Get vendor by ID",
          "@router.put(\"/{id}\")        # Update vendor details",
          "@router.delete(\"/{id}\")     # Soft-delete (set is_active=False)",
          "@router.post(\"/validate\")   # Check if GSTIN matches master — no DB write",
        ]),
        blank(),

        h3("3c. Verifier Extension — Vendor Validation"),
        blank(),
        ...code([
          "# order_bundle_verifier.py — extended vendor check",
          "def _vendor_master_check(vendor_po, vendor_invoice, checks, issues, db):",
          "    extracted_gstin = _field(vendor_invoice, \"vendor_gstin\")",
          "    if not extracted_gstin:",
          "        issues.append({\"code\": \"VENDOR_GSTIN_MISSING\", \"severity\": \"WARNING\", ...})",
          "        return",
          "    master = db.query(VendorRecord).filter_by(gstin=extracted_gstin).first()",
          "    if not master:",
          "        issues.append({\"code\": \"VENDOR_NOT_IN_MASTER\", \"severity\": \"WARNING\",",
          "                       \"message\": f\"GSTIN {extracted_gstin} not found in vendor master.\"})",
          "        return",
          "    if not _name_match(_field(vendor_invoice, \"vendor_name\"), master.legal_name):",
          "        issues.append({\"code\": \"VENDOR_NAME_MASTER_MISMATCH\", \"severity\": \"BLOCKER\", ...})",
        ]),
        blank(),

        h2("Consequences"),
        bullet("Tolerance is now percentage-based and configurable per check type. ±2% on a Rs 10 lakh invoice = Rs 2,000 tolerance (realistic). ±2 absolute on a Rs 10 lakh invoice is negligible and causes false PASSes on large amounts."),
        bullet("Line-item matching catches discrepancies that header-total matching misses. A vendor who changes a unit price by Rs 5 across 200 units but keeps the total the same will now be detected."),
        bullet("Vendor master validation blocks payment to unregistered GST numbers — a real fraud prevention mechanism."),
        bullet("Line-item parser adds complexity. Novel document layouts will require parser training. Recommend starting with the 3 known vendor invoice formats in the validation fixtures."),
        bullet("Vendor master requires initial population. Add a CSV bulk import endpoint for initial vendor list seeding."),
        bullet("The verifier function signature changes: db session is now a parameter. All tests that call verify_order_bundle() must be updated."),
        blank(),

        h2("Implementation Checklist"),
        p("Phase 1 — Tolerance (low effort, immediate value):"),
        num("Create backend/app/services/tolerance_config.py with ToleranceConfig dataclass"),
        num("Add tolerance env vars to Settings (TOLERANCE_CUSTOMER_PO_PCT, TOLERANCE_VENDOR_PO_PCT, etc.)"),
        num("Update _add_amount_check in order_bundle_verifier.py to use ToleranceConfig.within()"),
        num("Update existing tests that assert on REVIEW_REQUIRED due to ±2 hard-coding"),
        num("Run: python -m pytest tests -q and real-document validations — all baselines must pass"),
        blank(),
        p("Phase 2 — Vendor Master (medium effort):"),
        num("Create backend/app/models/vendor.py VendorRecord model"),
        num("Run: alembic revision --autogenerate -m add_vendors_table && alembic upgrade head"),
        num("Create backend/app/api/routes/vendors.py with CRUD endpoints"),
        num("Create backend/app/repositories/vendors.py with query helpers"),
        num("Extend verifier _vendor_procurement_status to call _vendor_master_check when db is provided"),
        num("Add vendor GSTIN extraction field to structured_text_parser vendor invoice field aliases"),
        num("Run full test suite and real-document validations"),
        blank(),
        p("Phase 3 — Line-Item Matching (high effort):"),
        num("Create backend/app/models/line_item.py LineItemRecord model"),
        num("Run: alembic revision --autogenerate -m add_line_items_table && alembic upgrade head"),
        num("Create backend/app/services/extraction/line_item_parser.py"),
        num("Integrate line_item_parser into extraction_service.py: after field extraction, run line item parse and persist LineItemRecords"),
        num("Extend NormalizedDocument to carry line_items: list[ParsedLineItem]"),
        num("Add _line_item_match() to order_bundle_verifier.py, call from _vendor_procurement_status"),
        num("Run all three real-document validation baselines — note that line-item check may flag new issues not in current baselines"),
        num("Update CLAUDE.md baseline acceptance criteria to include line-item check results"),
        blank(),

        pb(),

        // ══ 3. Implementation Plan ═════════════════════════════════════
        h1("3. Phased Implementation Plan"),
        p("All three ADRs are independent but have a recommended ordering. ADR-001 unlocks safe concurrent use, which is a prerequisite for ADR-002's multi-worker benefits. ADR-003 can proceed in parallel after ADR-001."),
        blank(),
        tbl([700, 2400, 1600, 1600, 3160], [
          [hdrCell("Phase", 700), hdrCell("ADR", 2400), hdrCell("Duration", 1600), hdrCell("Prerequisite", 1600), hdrCell("Acceptance Gate (CLAUDE.md)"), ],
          [cell("1"), cell("ADR-001: PostgreSQL + Alembic"), cell("3–5 days"), cell("None"), cell("pytest -q: 0 fail. All 3 real-doc baselines pass. No SQLite file in production.")],
          [cell("2"), cell("ADR-002: Async Queue (Celery)"), cell("5–8 days"), cell("ADR-001 (PostgreSQL)"), cell("pytest -q: 0 fail. Extraction survives worker restart. All baselines pass.")],
          [cell("3a"), cell("ADR-003: Tolerance config"), cell("1–2 days"), cell("ADR-001"), cell("pytest -q: 0 fail. Tolerance env-configurable. All baselines pass.")],
          [cell("3b"), cell("ADR-003: Vendor master"), cell("3–4 days"), cell("ADR-001"), cell("pytest -q: 0 fail. GSTIN validation check appears in bundle results.")],
          [cell("3c"), cell("ADR-003: Line-item matching"), cell("4–6 days"), cell("ADR-003b"), cell("pytest -q: 0 fail. LINE_ITEM_* checks appear in verification output. Baselines updated.")],
        ]),
        blank(),

        h2("Per-Phase Test Gate (CLAUDE.md §4)"),
        p("Every phase must complete all five steps before being declared done:"),
        num("Focused tests for the changed area — pass/skip/fail count required"),
        num("Migration tests: python -m pytest tests/integration/test_migrations.py -q"),
        num("Full backend test suite: python -m pytest tests -q — exact count required"),
        num("Fresh validation run: .\\scripts\\new-validation-run.ps1 -RunName <phase-name>-smoke"),
        num("Explicit confirmation that extraction, parser, OCR, verification, export, and frontend behavior are unchanged (or document what changed)"),
        blank(),

        // ══ 4. Risk Register ═══════════════════════════════════════════
        h1("4. Risk Register"),
        blank(),
        tbl([3000, 1400, 4060], [
          [hdrCell("Risk", 3000), hdrCell("Severity", 1400), hdrCell("Mitigation", 4060)],
          [cell("PostgreSQL migration corrupts existing bundle data"), statusCell("HIGH", "bad"), cell("Back up SQLite DB before migration. Use pgloader with dry-run. Validate row counts post-migration.")],
          [cell("Celery worker loses a job during deployment"), statusCell("MEDIUM", "warn"), cell("task_acks_late=True ensures jobs are re-queued on worker crash. Always drain queue before deploying worker.")],
          [cell("Line-item parser fails on new vendor invoice formats"), statusCell("MEDIUM", "warn"), cell("Fail gracefully: if line-item parse yields 0 items, skip line-item check rather than blocking extraction. Log as INFO.")],
          [cell("Tolerance change causes existing PASS checks to become REVIEW_REQUIRED"), statusCell("MEDIUM", "warn"), cell("Run all three real-doc baselines before and after. If % tolerance differs from ±2, accept the new more-correct result and update baseline notes.")],
          [cell("GSTIN validation blocks legitimate vendors not yet in master"), statusCell("LOW", "info"), cell("Initial vendor master check is WARNING severity only, not BLOCKER. Gradualism: warn first, block later once master is populated.")],
        ]),
        blank(),

        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 600 },
          children: [new TextRun({ text: "— End of Architecture Redesign Specification —", font: "Arial", size: 22, italics: true, color: "595959" })]
        }),
      ]
    }
  ]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('/sessions/upbeat-cool-albattani/mnt/order-assurance/Order-Assurance-Architecture-Redesign.docx', buf);
  console.log('Written: Order-Assurance-Architecture-Redesign.docx');
}).catch(e => { console.error(e.message); process.exit(1); });
