"""initial_schema

Revision ID: 1d6a128d1cc9
Revises: 
Create Date: 2026-06-22 07:25:37.877351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6a128d1cc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('order_bundle_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_document_id'), 'audit_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_order_bundle_id'), 'audit_events', ['order_bundle_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('has_digital_text', sa.Boolean(), nullable=True),
    sa.Column('rotation_detected', sa.Integer(), nullable=True),
    sa.Column('page_classification', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_pages_doc_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('field_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('candidate_value', sa.String(), nullable=True),
    sa.Column('normalized_value', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('text_source_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('evidence_text', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('selection_status', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_candidates_document_id'), 'field_candidates', ['document_id'], unique=False)
    op.create_index(op.f('ix_field_candidates_field_key'), 'field_candidates', ['field_key'], unique=False)
    op.create_index(op.f('ix_field_candidates_selection_status'), 'field_candidates', ['selection_status'], unique=False)
    op.create_index(op.f('ix_field_candidates_text_source_id'), 'field_candidates', ['text_source_id'], unique=False)
    op.create_table('order_bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bundle_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_po_no', sa.String(length=100), nullable=True),
    sa.Column('so_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('customer_delivery_status', sa.String(length=50), nullable=False),
    sa.Column('vendor_procurement_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_bundles_bundle_number'), 'order_bundles', ['bundle_number'], unique=True)
    op.create_table('text_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_version', sa.String(length=50), nullable=True),
    sa.Column('settings_hash', sa.String(length=64), nullable=False),
    sa.Column('settings_json', sa.String(length=2000), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('normalized_text', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', 'provider', 'settings_hash', 'image_hash', name='uq_text_sources_cache_key')
    )
    op.create_index(op.f('ix_text_sources_document_id'), 'text_sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_text_sources_provider'), 'text_sources', ['provider'], unique=False)
    op.create_table('bundle_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_bundle_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_bundle_id'], ['order_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_documents_document_type'), 'bundle_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_bundle_documents_order_bundle_id'), 'bundle_documents', ['order_bundle_id'], unique=False)
    op.create_table('document_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('primary_ref_no', sa.String(length=150), nullable=True),
    sa.Column('po_ref_no', sa.String(length=150), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['bundle_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_metadata_document_id'), 'document_metadata', ['document_id'], unique=True)
    op.create_table('reference_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('order_bundle_id', sa.String(length=36), nullable=True),
    sa.Column('reference_type', sa.String(length=80), nullable=False),
    sa.Column('reference_value', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['bundle_documents.id'], ),
    sa.ForeignKeyConstraint(['order_bundle_id'], ['order_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_index_document_id'), 'reference_index', ['document_id'], unique=False)
    op.create_index(op.f('ix_reference_index_document_type'), 'reference_index', ['document_type'], unique=False)
    op.create_index(op.f('ix_reference_index_order_bundle_id'), 'reference_index', ['order_bundle_id'], unique=False)
    op.create_index(op.f('ix_reference_index_reference_type'), 'reference_index', ['reference_type'], unique=False)
    op.create_index(op.f('ix_reference_index_reference_value'), 'reference_index', ['reference_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_index_reference_value'), table_name='reference_index')
    op.drop_index(op.f('ix_reference_index_reference_type'), table_name='reference_index')
    op.drop_index(op.f('ix_reference_index_order_bundle_id'), table_name='reference_index')
    op.drop_index(op.f('ix_reference_index_document_type'), table_name='reference_index')
    op.drop_index(op.f('ix_reference_index_document_id'), table_name='reference_index')
    op.drop_table('reference_index')
    op.drop_index(op.f('ix_document_metadata_document_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_bundle_documents_order_bundle_id'), table_name='bundle_documents')
    op.drop_index(op.f('ix_bundle_documents_document_type'), table_name='bundle_documents')
    op.drop_table('bundle_documents')
    op.drop_index(op.f('ix_text_sources_provider'), table_name='text_sources')
    op.drop_index(op.f('ix_text_sources_document_id'), table_name='text_sources')
    op.drop_table('text_sources')
    op.drop_index(op.f('ix_order_bundles_bundle_number'), table_name='order_bundles')
    op.drop_table('order_bundles')
    op.drop_index(op.f('ix_field_candidates_text_source_id'), table_name='field_candidates')
    op.drop_index(op.f('ix_field_candidates_selection_status'), table_name='field_candidates')
    op.drop_index(op.f('ix_field_candidates_field_key'), table_name='field_candidates')
    op.drop_index(op.f('ix_field_candidates_document_id'), table_name='field_candidates')
    op.drop_table('field_candidates')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_audit_events_order_bundle_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_document_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
