"""add_tenant_id_all_tables

Revision ID: 35886ce97adc
Revises: 56192bbcdd68
Create Date: 2026-06-22 07:39:40.167081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35886ce97adc'
down_revision: Union[str, Sequence[str], None] = '56192bbcdd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('tenant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.add_column('bundle_documents', sa.Column('tenant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_bundle_documents_tenant_id'), 'bundle_documents', ['tenant_id'], unique=False)
    op.add_column('document_metadata', sa.Column('tenant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_document_metadata_tenant_id'), 'document_metadata', ['tenant_id'], unique=False)
    op.add_column('order_bundles', sa.Column('tenant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_order_bundles_tenant_id'), 'order_bundles', ['tenant_id'], unique=False)
    op.add_column('reference_index', sa.Column('tenant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_reference_index_tenant_id'), 'reference_index', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_index_tenant_id'), table_name='reference_index')
    op.drop_column('reference_index', 'tenant_id')
    op.drop_index(op.f('ix_order_bundles_tenant_id'), table_name='order_bundles')
    op.drop_column('order_bundles', 'tenant_id')
    op.drop_index(op.f('ix_document_metadata_tenant_id'), table_name='document_metadata')
    op.drop_column('document_metadata', 'tenant_id')
    op.drop_index(op.f('ix_bundle_documents_tenant_id'), table_name='bundle_documents')
    op.drop_column('bundle_documents', 'tenant_id')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_column('audit_events', 'tenant_id')
    # ### end Alembic commands ###
