"""chain_validation_fields

Revision ID: 42236a0b1c36
Revises: g9h0i1j2k3l4
Create Date: 2026-04-11 10:23:31.981728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42236a0b1c36'
down_revision: Union[str, None] = 'g9h0i1j2k3l4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create new enum types required for purchase_orders columns (DO block handles IF NOT EXISTS)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE billingtype AS ENUM ('full', 'staged', 'recurring');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE chainstatus AS ENUM ('incomplete', 'complete', 'verified', 'mismatch');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)

    # Add new values to existing documenttype enum (autogenerate misses these)
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'INSTALLATION_REPORT'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'VENDOR_CREDIT_NOTE'")

    # Safe drops before batch alter
    op.execute("DROP INDEX IF EXISTS idx_document_status")
    op.execute("ALTER TABLE documents DROP CONSTRAINT IF EXISTS uq_doc_per_po_type")
    op.execute("DROP INDEX IF EXISTS ix_corr_document_id")
    op.execute("DROP INDEX IF EXISTS idx_ref_value_trgm")
    op.execute("DROP INDEX IF EXISTS ix_reference_index_ref_value")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('so_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vpo_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('billing_stage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extraction_ok', sa.Boolean(), server_default='true', nullable=False))
        batch_op.create_index('ix_doc_so_number', ['so_number'], unique=False)
        batch_op.create_unique_constraint('uq_doc_per_po', ['po_id', 'checksum'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_type', sa.Enum('full', 'staged', 'recurring', name='billingtype'), server_default='full', nullable=False))
        batch_op.add_column(sa.Column('billing_milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('requires_install_report', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('chain_status', sa.Enum('incomplete', 'complete', 'verified', 'mismatch', name='chainstatus'), server_default='incomplete', nullable=False))

    with op.batch_alter_table('reference_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_index_ref_value'), ['ref_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: PostgreSQL does not support removing enum values.
    # INSTALLATION_REPORT and VENDOR_CREDIT_NOTE remain in documenttype after downgrade.

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_index_ref_value'))
        batch_op.create_index('idx_ref_value_trgm', ['ref_value'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('chain_status')
        batch_op.drop_column('requires_install_report')
        batch_op.drop_column('billing_milestones')
        batch_op.drop_column('billing_type')

    op.execute("DROP TYPE IF EXISTS chainstatus")
    op.execute("DROP TYPE IF EXISTS billingtype")

    with op.batch_alter_table('extraction_corrections', schema=None) as batch_op:
        batch_op.create_index('ix_corr_document_id', ['document_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_doc_per_po', type_='unique')
        batch_op.drop_index('ix_doc_so_number')
        batch_op.create_unique_constraint('uq_doc_per_po_type', ['po_id', 'document_type', 'checksum'])
        batch_op.create_index('idx_document_status', ['status'], unique=False)
        batch_op.drop_column('extraction_ok')
        batch_op.drop_column('billing_stage')
        batch_op.drop_column('vpo_numbers')
        batch_op.drop_column('so_number')

    # ### end Alembic commands ###
