"""add_celery_task_id_last_verified_at

Revision ID: 56192bbcdd68
Revises: 1d6a128d1cc9
Create Date: 2026-06-22 07:35:53.293821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56192bbcdd68'
down_revision: Union[str, Sequence[str], None] = '1d6a128d1cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_documents', sa.Column('celery_task_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bundle_documents_celery_task_id'), 'bundle_documents', ['celery_task_id'], unique=False)
    op.add_column('order_bundles', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_bundles', 'last_verified_at')
    op.drop_index(op.f('ix_bundle_documents_celery_task_id'), table_name='bundle_documents')
    op.drop_column('bundle_documents', 'celery_task_id')
    # ### end Alembic commands ###
