"""initial schema

Revision ID: 6e44882e6975
Revises: 
Create Date: 2026-02-16 15:16:18.199891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e44882e6975'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity_id')
        batch_op.drop_index('ix_audit_logs_entity_type')

    op.drop_table('audit_logs')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Business ID like SKY-AB1234, used as NAS folder name',
               existing_comment='Business ID like SKY-AB1234',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name like Acme Corp',
               existing_nullable=False)
        batch_op.create_index('ix_customers_gst', ['gst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_gst_number'), ['gst_number'], unique=False)

    with op.batch_alter_table('document_metadata', schema=None) as batch_op:
        batch_op.alter_column('model_version',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index('ix_document_metadata_document_id')
        batch_op.create_index(batch_op.f('ix_document_metadata_doc_date'), ['doc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_metadata_status'), ['status'], unique=False)
        batch_op.create_index('ix_meta_doc_date', ['doc_date'], unique=False)
        batch_op.create_index('ix_meta_document_id', ['document_id'], unique=True)
        batch_op.create_index('ix_meta_extracted_data', ['extracted_data'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_meta_po_ref', ['po_ref_no'], unique=False)
        batch_op.create_index('ix_meta_primary_ref', ['primary_ref_no'], unique=False)
        batch_op.create_index('ix_meta_status', ['status'], unique=False)
        batch_op.create_unique_constraint(None, ['document_id'])
        batch_op.drop_constraint('document_metadata_verified_by_fkey', type_='foreignkey')
        batch_op.drop_column('verified_by')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               comment='UUID-prefixed stored name',
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment="User's original filename",
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Relative NAS path',
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               comment='File size in bytes',
               existing_nullable=False)
        batch_op.alter_column('checksum',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hex',
               existing_comment='SHA-256',
               existing_nullable=False)
        batch_op.drop_index('ix_documents_po_id')
        batch_op.drop_constraint('uq_doc_po_type_checksum', type_='unique')
        batch_op.create_index('ix_doc_checksum', ['checksum'], unique=False)
        batch_op.create_index('ix_doc_po_id', ['po_id'], unique=False)
        batch_op.create_index('ix_doc_status', ['status'], unique=False)
        batch_op.create_index('ix_doc_type', ['document_type'], unique=False)
        batch_op.create_unique_constraint('uq_doc_per_po_type', ['po_id', 'document_type', 'checksum'])
        batch_op.drop_constraint('documents_uploaded_by_fkey', type_='foreignkey')
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_orders_customer_id')
        batch_op.drop_index('ix_purchase_orders_po_number')
        batch_op.create_index('ix_po_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_po_date', ['po_date'], unique=False)
        batch_op.create_index('ix_po_number', ['po_number'], unique=True)
        batch_op.create_index('ix_po_status', ['status'], unique=False)
        batch_op.create_unique_constraint(None, ['po_number'])
        batch_op.drop_constraint('purchase_orders_created_by_fkey', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('reference_index', schema=None) as batch_op:
        batch_op.alter_column('po_id',
               existing_type=sa.UUID(),
               comment='Denormalized for speed',
               existing_comment='Denormalized for fast lookup',
               existing_nullable=False)
        batch_op.alter_column('ref_type',
               existing_type=sa.VARCHAR(length=50),
               comment='e.g. invoice_number, dc_number, po_number',
               existing_comment='e.g. "invoice_number", "dc_number", "po_number"',
               existing_nullable=False)
        batch_op.alter_column('ref_value',
               existing_type=sa.VARCHAR(length=255),
               comment='The actual reference value',
               existing_nullable=False)
        batch_op.drop_index('ix_reference_index_document_id')
        batch_op.drop_index('ix_reference_index_po_id')
        batch_op.create_index('ix_ref_document_id', ['document_id'], unique=False)
        batch_op.create_index('ix_ref_po_id', ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_index_ref_value'), ['ref_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_index_ref_value'))
        batch_op.drop_index('ix_ref_po_id')
        batch_op.drop_index('ix_ref_document_id')
        batch_op.create_index('ix_reference_index_po_id', ['po_id'], unique=False)
        batch_op.create_index('ix_reference_index_document_id', ['document_id'], unique=False)
        batch_op.alter_column('ref_value',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='The actual reference value',
               existing_nullable=False)
        batch_op.alter_column('ref_type',
               existing_type=sa.VARCHAR(length=50),
               comment='e.g. "invoice_number", "dc_number", "po_number"',
               existing_comment='e.g. invoice_number, dc_number, po_number',
               existing_nullable=False)
        batch_op.alter_column('po_id',
               existing_type=sa.UUID(),
               comment='Denormalized for fast lookup',
               existing_comment='Denormalized for speed',
               existing_nullable=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('purchase_orders_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_po_status')
        batch_op.drop_index('ix_po_number')
        batch_op.drop_index('ix_po_date')
        batch_op.drop_index('ix_po_customer_id')
        batch_op.create_index('ix_purchase_orders_po_number', ['po_number'], unique=True)
        batch_op.create_index('ix_purchase_orders_customer_id', ['customer_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('documents_uploaded_by_fkey', 'users', ['uploaded_by'], ['id'])
        batch_op.drop_constraint('uq_doc_per_po_type', type_='unique')
        batch_op.drop_index('ix_doc_type')
        batch_op.drop_index('ix_doc_status')
        batch_op.drop_index('ix_doc_po_id')
        batch_op.drop_index('ix_doc_checksum')
        batch_op.create_unique_constraint('uq_doc_po_type_checksum', ['po_id', 'document_type', 'checksum'])
        batch_op.create_index('ix_documents_po_id', ['po_id'], unique=False)
        batch_op.alter_column('checksum',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256',
               existing_comment='SHA-256 hex',
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File size in bytes',
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Relative NAS path',
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's original filename",
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UUID-prefixed stored name',
               existing_nullable=False)

    with op.batch_alter_table('document_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('document_metadata_verified_by_fkey', 'users', ['verified_by'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_meta_status')
        batch_op.drop_index('ix_meta_primary_ref')
        batch_op.drop_index('ix_meta_po_ref')
        batch_op.drop_index('ix_meta_extracted_data', postgresql_using='gin')
        batch_op.drop_index('ix_meta_document_id')
        batch_op.drop_index('ix_meta_doc_date')
        batch_op.drop_index(batch_op.f('ix_document_metadata_status'))
        batch_op.drop_index(batch_op.f('ix_document_metadata_doc_date'))
        batch_op.create_index('ix_document_metadata_document_id', ['document_id'], unique=True)
        batch_op.alter_column('model_version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_gst_number'))
        batch_op.drop_index('ix_customers_gst')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name like Acme Corp',
               existing_nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Business ID like SKY-AB1234',
               existing_comment='Business ID like SKY-AB1234, used as NAS folder name',
               existing_nullable=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='audit_logs_actor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_id', ['entity_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'VIEWER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    # ### end Alembic commands ###
