from __future__ import annotations

from enum import Enum


class DocumentType(str, Enum):
    CUSTOMER_PO = "CUSTOMER_PO"
    COMPANY_INVOICE = "COMPANY_INVOICE"
    CUSTOMER_INVOICE = "CUSTOMER_INVOICE"
    COMPANY_DC = "COMPANY_DC"
    DELIVERY_CHALLAN = "DELIVERY_CHALLAN"
    COMPANY_PO = "COMPANY_PO"
    VENDOR_PO = "VENDOR_PO"
    VENDOR_INVOICE = "VENDOR_INVOICE"
    VENDOR_BILL = "VENDOR_BILL"
    ERP_ORDER_EXPORT = "ERP_ORDER_EXPORT"


class BundleStatus(str, Enum):
    OK = "OK"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    MISMATCH = "MISMATCH"
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    BLOCKED = "BLOCKED"
    APPROVED = "APPROVED"
    CLOSED = "CLOSED"


class SectionStatus(str, Enum):
    PASS = "PASS"
    PARTIAL_PASS = "PARTIAL_PASS"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    MISMATCH = "MISMATCH"
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    BLOCKED = "BLOCKED"


class CheckResult(str, Enum):
    PASS = "PASS"
    PARTIAL_PASS = "PARTIAL_PASS"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    MISMATCH = "MISMATCH"
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    BLOCKED = "BLOCKED"


class CheckSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKER = "BLOCKER"


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    EXTRACTING = "EXTRACTING"
    PENDING_REVIEW = "PENDING_REVIEW"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class MetadataStatus(str, Enum):
    PENDING = "PENDING"
    EXTRACTED = "EXTRACTED"
    FAILED = "FAILED"
    MANUAL_ENTRY = "MANUAL_ENTRY"
